/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.orange.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Messaging service. Represents a row in the &quot;OBS_Messaging&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.orange.model.impl.MessagingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.orange.model.impl.MessagingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Messaging
 * @generated
 */
@ProviderType
public interface MessagingModel
	extends BaseModel<Messaging>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a messaging model instance should use the {@link Messaging} interface instead.
	 */

	/**
	 * Returns the primary key of this messaging.
	 *
	 * @return the primary key of this messaging
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this messaging.
	 *
	 * @param primaryKey the primary key of this messaging
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this messaging.
	 *
	 * @return the uuid of this messaging
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this messaging.
	 *
	 * @param uuid the uuid of this messaging
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id message of this messaging.
	 *
	 * @return the id message of this messaging
	 */
	public long getIdMessage();

	/**
	 * Sets the id message of this messaging.
	 *
	 * @param idMessage the id message of this messaging
	 */
	public void setIdMessage(long idMessage);

	/**
	 * Returns the group ID of this messaging.
	 *
	 * @return the group ID of this messaging
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this messaging.
	 *
	 * @param groupId the group ID of this messaging
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this messaging.
	 *
	 * @return the company ID of this messaging
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this messaging.
	 *
	 * @param companyId the company ID of this messaging
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this messaging.
	 *
	 * @return the create date of this messaging
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this messaging.
	 *
	 * @param createDate the create date of this messaging
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this messaging.
	 *
	 * @return the modified date of this messaging
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this messaging.
	 *
	 * @param modifiedDate the modified date of this messaging
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the content of this messaging.
	 *
	 * @return the content of this messaging
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this messaging.
	 *
	 * @param content the content of this messaging
	 */
	public void setContent(String content);

	/**
	 * Returns the id event of this messaging.
	 *
	 * @return the id event of this messaging
	 */
	public long getIdEvent();

	/**
	 * Sets the id event of this messaging.
	 *
	 * @param idEvent the id event of this messaging
	 */
	public void setIdEvent(long idEvent);

	@Override
	public Messaging cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}