/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.orange.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.orange.model.Messaging;
import com.orange.model.MessagingModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Messaging service. Represents a row in the &quot;OBS_Messaging&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MessagingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MessagingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MessagingImpl
 * @generated
 */
@JSON(strict = true)
public class MessagingModelImpl
	extends BaseModelImpl<Messaging> implements MessagingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a messaging model instance should use the <code>Messaging</code> interface instead.
	 */
	public static final String TABLE_NAME = "OBS_Messaging";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"idMessage", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"content", Types.VARCHAR}, {"idEvent", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idMessage", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idEvent", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OBS_Messaging (uuid_ VARCHAR(75) null,idMessage LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,content VARCHAR(75) null,idEvent LONG)";

	public static final String TABLE_SQL_DROP = "drop table OBS_Messaging";

	public static final String ORDER_BY_JPQL =
		" ORDER BY messaging.idMessage ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OBS_Messaging.idMessage ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDMESSAGE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MessagingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idMessage;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdMessage(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idMessage;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Messaging.class;
	}

	@Override
	public String getModelClassName() {
		return Messaging.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Messaging, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Messaging, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Messaging, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Messaging)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Messaging, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Messaging, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Messaging)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Messaging, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Messaging, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Messaging, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Messaging, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Messaging, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Messaging, Object>>();
		Map<String, BiConsumer<Messaging, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Messaging, ?>>();

		attributeGetterFunctions.put("uuid", Messaging::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Messaging, String>)Messaging::setUuid);
		attributeGetterFunctions.put("idMessage", Messaging::getIdMessage);
		attributeSetterBiConsumers.put(
			"idMessage", (BiConsumer<Messaging, Long>)Messaging::setIdMessage);
		attributeGetterFunctions.put("groupId", Messaging::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Messaging, Long>)Messaging::setGroupId);
		attributeGetterFunctions.put("companyId", Messaging::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Messaging, Long>)Messaging::setCompanyId);
		attributeGetterFunctions.put("createDate", Messaging::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Messaging, Date>)Messaging::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Messaging::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Messaging, Date>)Messaging::setModifiedDate);
		attributeGetterFunctions.put("content", Messaging::getContent);
		attributeSetterBiConsumers.put(
			"content", (BiConsumer<Messaging, String>)Messaging::setContent);
		attributeGetterFunctions.put("idEvent", Messaging::getIdEvent);
		attributeSetterBiConsumers.put(
			"idEvent", (BiConsumer<Messaging, Long>)Messaging::setIdEvent);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getIdMessage() {
		return _idMessage;
	}

	@Override
	public void setIdMessage(long idMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idMessage = idMessage;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return "";
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_content = content;
	}

	@JSON
	@Override
	public long getIdEvent() {
		return _idEvent;
	}

	@Override
	public void setIdEvent(long idEvent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idEvent = idEvent;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Messaging.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Messaging.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Messaging toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Messaging>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MessagingImpl messagingImpl = new MessagingImpl();

		messagingImpl.setUuid(getUuid());
		messagingImpl.setIdMessage(getIdMessage());
		messagingImpl.setGroupId(getGroupId());
		messagingImpl.setCompanyId(getCompanyId());
		messagingImpl.setCreateDate(getCreateDate());
		messagingImpl.setModifiedDate(getModifiedDate());
		messagingImpl.setContent(getContent());
		messagingImpl.setIdEvent(getIdEvent());

		messagingImpl.resetOriginalValues();

		return messagingImpl;
	}

	@Override
	public Messaging cloneWithOriginalValues() {
		MessagingImpl messagingImpl = new MessagingImpl();

		messagingImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		messagingImpl.setIdMessage(
			this.<Long>getColumnOriginalValue("idMessage"));
		messagingImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		messagingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		messagingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		messagingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		messagingImpl.setContent(
			this.<String>getColumnOriginalValue("content"));
		messagingImpl.setIdEvent(this.<Long>getColumnOriginalValue("idEvent"));

		return messagingImpl;
	}

	@Override
	public int compareTo(Messaging messaging) {
		long primaryKey = messaging.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Messaging)) {
			return false;
		}

		Messaging messaging = (Messaging)object;

		long primaryKey = messaging.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Messaging> toCacheModel() {
		MessagingCacheModel messagingCacheModel = new MessagingCacheModel();

		messagingCacheModel.uuid = getUuid();

		String uuid = messagingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			messagingCacheModel.uuid = null;
		}

		messagingCacheModel.idMessage = getIdMessage();

		messagingCacheModel.groupId = getGroupId();

		messagingCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			messagingCacheModel.createDate = createDate.getTime();
		}
		else {
			messagingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			messagingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			messagingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		messagingCacheModel.content = getContent();

		String content = messagingCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			messagingCacheModel.content = null;
		}

		messagingCacheModel.idEvent = getIdEvent();

		return messagingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Messaging, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Messaging, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Messaging, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Messaging)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Messaging>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Messaging.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _idMessage;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _content;
	private long _idEvent;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Messaging, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Messaging)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("idMessage", _idMessage);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("content", _content);
		_columnOriginalValues.put("idEvent", _idEvent);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("idMessage", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("content", 64L);

		columnBitmasks.put("idEvent", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Messaging _escapedModel;

}