/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.orange.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.orange.model.Transport;
import com.orange.model.TransportModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Transport service. Represents a row in the &quot;OBS_Transport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TransportModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TransportImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TransportImpl
 * @generated
 */
@JSON(strict = true)
public class TransportModelImpl
	extends BaseModelImpl<Transport> implements TransportModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a transport model instance should use the <code>Transport</code> interface instead.
	 */
	public static final String TABLE_NAME = "OBS_Transport";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"idTransport", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"collec", Types.BOOLEAN}, {"prive", Types.BOOLEAN},
		{"idEvent", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idTransport", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("collec", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("prive", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("idEvent", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OBS_Transport (uuid_ VARCHAR(75) null,idTransport LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,collec BOOLEAN,prive BOOLEAN,idEvent LONG)";

	public static final String TABLE_SQL_DROP = "drop table OBS_Transport";

	public static final String ORDER_BY_JPQL =
		" ORDER BY transport.idTransport ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OBS_Transport.idTransport ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDTRANSPORT_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TransportModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idTransport;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdTransport(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idTransport;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Transport.class;
	}

	@Override
	public String getModelClassName() {
		return Transport.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Transport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Transport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Transport, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Transport)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Transport, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Transport, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Transport)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Transport, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Transport, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Transport, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Transport, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Transport, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Transport, Object>>();
		Map<String, BiConsumer<Transport, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Transport, ?>>();

		attributeGetterFunctions.put("uuid", Transport::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Transport, String>)Transport::setUuid);
		attributeGetterFunctions.put("idTransport", Transport::getIdTransport);
		attributeSetterBiConsumers.put(
			"idTransport",
			(BiConsumer<Transport, Long>)Transport::setIdTransport);
		attributeGetterFunctions.put("groupId", Transport::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Transport, Long>)Transport::setGroupId);
		attributeGetterFunctions.put("companyId", Transport::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Transport, Long>)Transport::setCompanyId);
		attributeGetterFunctions.put("createDate", Transport::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Transport, Date>)Transport::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Transport::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Transport, Date>)Transport::setModifiedDate);
		attributeGetterFunctions.put("collec", Transport::getCollec);
		attributeSetterBiConsumers.put(
			"collec", (BiConsumer<Transport, Boolean>)Transport::setCollec);
		attributeGetterFunctions.put("prive", Transport::getPrive);
		attributeSetterBiConsumers.put(
			"prive", (BiConsumer<Transport, Boolean>)Transport::setPrive);
		attributeGetterFunctions.put("idEvent", Transport::getIdEvent);
		attributeSetterBiConsumers.put(
			"idEvent", (BiConsumer<Transport, Long>)Transport::setIdEvent);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getIdTransport() {
		return _idTransport;
	}

	@Override
	public void setIdTransport(long idTransport) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idTransport = idTransport;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getCollec() {
		return _collec;
	}

	@JSON
	@Override
	public boolean isCollec() {
		return _collec;
	}

	@Override
	public void setCollec(boolean collec) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_collec = collec;
	}

	@JSON
	@Override
	public boolean getPrive() {
		return _prive;
	}

	@JSON
	@Override
	public boolean isPrive() {
		return _prive;
	}

	@Override
	public void setPrive(boolean prive) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prive = prive;
	}

	@JSON
	@Override
	public long getIdEvent() {
		return _idEvent;
	}

	@Override
	public void setIdEvent(long idEvent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idEvent = idEvent;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Transport.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Transport.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Transport toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Transport>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TransportImpl transportImpl = new TransportImpl();

		transportImpl.setUuid(getUuid());
		transportImpl.setIdTransport(getIdTransport());
		transportImpl.setGroupId(getGroupId());
		transportImpl.setCompanyId(getCompanyId());
		transportImpl.setCreateDate(getCreateDate());
		transportImpl.setModifiedDate(getModifiedDate());
		transportImpl.setCollec(isCollec());
		transportImpl.setPrive(isPrive());
		transportImpl.setIdEvent(getIdEvent());

		transportImpl.resetOriginalValues();

		return transportImpl;
	}

	@Override
	public Transport cloneWithOriginalValues() {
		TransportImpl transportImpl = new TransportImpl();

		transportImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		transportImpl.setIdTransport(
			this.<Long>getColumnOriginalValue("idTransport"));
		transportImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		transportImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		transportImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		transportImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		transportImpl.setCollec(this.<Boolean>getColumnOriginalValue("collec"));
		transportImpl.setPrive(this.<Boolean>getColumnOriginalValue("prive"));
		transportImpl.setIdEvent(this.<Long>getColumnOriginalValue("idEvent"));

		return transportImpl;
	}

	@Override
	public int compareTo(Transport transport) {
		long primaryKey = transport.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Transport)) {
			return false;
		}

		Transport transport = (Transport)object;

		long primaryKey = transport.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Transport> toCacheModel() {
		TransportCacheModel transportCacheModel = new TransportCacheModel();

		transportCacheModel.uuid = getUuid();

		String uuid = transportCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			transportCacheModel.uuid = null;
		}

		transportCacheModel.idTransport = getIdTransport();

		transportCacheModel.groupId = getGroupId();

		transportCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			transportCacheModel.createDate = createDate.getTime();
		}
		else {
			transportCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			transportCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			transportCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		transportCacheModel.collec = isCollec();

		transportCacheModel.prive = isPrive();

		transportCacheModel.idEvent = getIdEvent();

		return transportCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Transport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Transport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Transport, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Transport)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Transport>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Transport.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _idTransport;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _collec;
	private boolean _prive;
	private long _idEvent;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Transport, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Transport)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("idTransport", _idTransport);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("collec", _collec);
		_columnOriginalValues.put("prive", _prive);
		_columnOriginalValues.put("idEvent", _idEvent);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("idTransport", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("collec", 64L);

		columnBitmasks.put("prive", 128L);

		columnBitmasks.put("idEvent", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Transport _escapedModel;

}